"""Subclass of MyFrame1, which is generated by wxFormBuilder."""

import wx
import gui

# Implementing MyFrame1
class stock_class( gui.MyFrame1 ):
	def __init__( self, parent ):
		gui.MyFrame1.__init__( self, parent )
	
	# Handlers for MyFrame1 events.
	def generate_stock_panel( self, event ):
		# TODO: Implement generate_stock_panel
		pass
	
	def update( self, event ):
		# TODO: Implement update
		pass
	
	def update_log( self, event ):
		# TODO: Implement update_log
		pass
	
	
